### ISSUE TITLE
Evaluation on questions with blank explanations

### ISSUE THREAD

**Issue by jenlindadsouza** [umanlp/tg2019task#2] opened 2019-06-15 07:50 UTC
Dear organizers,

Running another dataset check showed the following:

203 Questions in the Training set have no explanations; So of the 1190 training instances, we actually have 987. [Ref Data File: ARC-Elementary+EXPL-Train.tsv]

37 Questions in the Dev set have no explanations; So of the 264 dev instances, 227 comprise the dev set. [Ref Data File: ARC-Elementary+EXPL-Dev.tsv]

I also tried making a submission with the dev set gold annotations for explanations (please find as attachment to this message) and it gave a 0.999874 MAP. Could we have some clarification on how to handle these blank QA instances so we are in a uniform evaluation setting?

Thank you very much!

[predict.txt](https://github.com/umanlp/tg2019task/files/3292840/predict.txt)

**Comment by dustalov** [comment] 2019-06-16 14:14
I think the problem is caused by the not-very-strict evaluation code that does not take into account the blank explanations. I will inspect the code very soon.

**Comment by jenlindadsouza** [comment] 2019-06-17 05:28
Somehow related... We've just found about 60 explanation sentences to be mapped to different identifiers (please find the sentences in attached file). [Ref: expl-tablestore.csv]. Please let us which identifiers to use for the submissions. Thank you! 

[one-to-many-map-sentence-IDs.txt](https://github.com/umanlp/tg2019task/files/3295364/one-to-many-map-sentence-IDs.txt)

**Comment by PeterAJansen** [comment] 2019-06-17 05:51
1) Hmm, 0.999874 is very close to being off by 1/5000, the approximate number of rows in the tablestore.  I suspect this might be something simple, likely a case issue due to the one row whose UUID was overwritten by one of the annotators with the word "Good" (with the capital "G").  In the short term, because the difference is isn't until the 4th decimal place, I think it's safe to develop/evaluate and still have a solid estimate of performance. 

2) I've just added the Scala baseline code for the task ( https://github.com/cognitiveailab/explanationreconstructiontextgaphs2019 ).  It achieves a MAP of ~0.28.  The main difference is that it performs a tf.idf evaluation of each tablestore row's utility for a given question independently, rather than doing it jointly as in the Python baseline example.

3) Could you describe the issue with the 60 explanation sentences in more detail?  

thanks!

**Comment by jenlindadsouza** [comment] 2019-06-17 05:58
Thank you for the reply. 

I can confirm explanation sentence 'a food contains nutrients for living things' has ID as Good.

About the issue with the 60 explanation sentences, please find one instance below. So this sentence 'an animal is a kind of living thing' appears twice in expl-tablestore.csv as shown below with different identifiers:

bb63-bcc5-0cd8-72db	an animal is a kind of living thing
34b7-df26-54b7-5ad8	an animal is a kind of living thing

This happens with 59 other explanation sentences. They are listed in the file (one-to-many-map-sentence-IDs.txt) I shared as attachment.

**Comment by PeterAJansen** [comment] 2019-06-17 06:20
Thanks for this question!  Any rows in the Tablestore with a non-zero amount of text in the [SKIP] DEP column have been deprecated.  This is completed as part of the quality assurance checks as the annotators find accidental duplicate facts in the explanations, and standardize these to point to a single UUID.  Internally to keep an audit trail we rarely delete facts from the Tablestore, but only deprecate them -- but clearly that's very confusing here, and I should have deleted them before this release.  My apologies!

Pragmatically, the duplicates tend to look as such (with the deprecation message populated in their DEP column):

KINDOF.tsv:a    block   is a kind of            object                                                          aa85-b969-a168-ebce
KINDOF.tsv:a    block   is a kind of            object                                                  Duplicate. All uses deleted.    7345-8be9-7302-3f50


The one place there may not be deprecation messages is in the handful of tables drawn from the earlier AI2 Aristo Tablestore (this is mainly the country location tables, as in 'Zimbabwe is located in the southern hemisphere').  It's possible that we expanded this table at some point without checking for duplicates.  Thankfully none of these rows should be used in an explanation, and contain low frequency terms for the science exam corpus (for example, "Zimbabwe" shouldn't occur in any of the questions), so I wouldn't expect this would cause a decrease in performance -- either one of the duplicate rows would be marked as "incorrect".

**Comment by jenlindadsouza** [comment] 2019-06-17 08:41
Ok, thank you for the clarification.

Sharing here the explanation tablestore I generated with duplicates removed. For the instances without deprecation or 'moved to' messages as in the example you pointed out, we pick the first identifier encountered.

[expl-tablestore-cleaned.txt](https://github.com/umanlp/tg2019task/files/3295962/expl-tablestore-cleaned.txt)

Also, I share all the exception cases that were found without deprecation messages in the file below.

[expl-tablestore-exceptions.txt](https://github.com/umanlp/tg2019task/files/3295967/expl-tablestore-exceptions.txt)

If it possible for you'll to confirm our cleaned data as valid, we would much appreciate that! Thank you very much!

**Closed** 2019-08-01 13:27 UTC
